# Generated by Django 3.1.1 on 2020-10-29 03:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0002_auto_20201029_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=288, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=288, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=288, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EventBranchVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=288)),
                ('address', models.TextField()),
                ('email', models.CharField(blank=True, max_length=288, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=288, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.orgprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=288)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('last_registration_date', models.DateField()),
                ('session_per_week', models.PositiveIntegerField()),
                ('session_start_time', models.TimeField()),
                ('session_end_time', models.TimeField()),
                ('day', models.CharField(default='Sunday & Monday', max_length=288)),
                ('thumbnail', models.ImageField(upload_to='events/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('content', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
                ('top_rated', models.BooleanField(blank=True, default=False, null=True)),
                ('most_popular', models.BooleanField(blank=True, default=False, null=True)),
                ('best_sell', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventbranchvenue')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventcategory')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.orgprofile')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventsubcategory')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.trainerprofile')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
            ],
        ),
    ]
