# Generated by Django 3.1.1 on 2020-09-17 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbranchvenue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.orgprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='branch_venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventbranchvenue'),
        ),
        migrations.AddField(
            model_name='event',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.orgprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventsubcategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.trainerprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventtype'),
        ),
    ]
