# Generated by Django 3.1.1 on 2020-10-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20201012_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='ending_date',
            field=models.DateField(default='2020-05-05'),
            preserve_default=False,
        ),
    ]
