# Generated by Django 3.1.1 on 2020-09-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200913_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbranchvenue',
            name='user',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='user',
        ),
    ]
