# Generated by Django 3.1.1 on 2020-10-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20201012_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.CharField(default='Sunday & Monday', max_length=288),
        ),
    ]
