# Generated by Django 3.1.1 on 2020-10-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='most_popular',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='top_rated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
