# Generated by Django 3.1.1 on 2020-10-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201009_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='best_sell',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
