# Generated by Django 3.1.1 on 2020-09-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200913_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbranchvenue',
            name='name',
            field=models.CharField(max_length=288, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=288, unique=True),
        ),
    ]
