# Generated by Django 3.1.1 on 2020-10-13 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=288, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=588, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=588, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=588, null=True),
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=288, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=288, null=True)),
                ('email', models.CharField(max_length=288)),
                ('address', models.CharField(blank=True, max_length=288, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=588, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=588, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=588, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
