# Generated by Django 3.1.1 on 2020-09-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=588, null=True),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=588, null=True),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=588, null=True),
        ),
    ]
