# Generated by Django 3.1.1 on 2020-10-29 03:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='education',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='experience',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/'),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=288, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=288, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='email',
            field=models.CharField(max_length=288, unique=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=588, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=588, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=588, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=288, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('contact_number', models.CharField(blank=True, max_length=288, null=True)),
                ('email', models.CharField(max_length=288)),
                ('address', models.CharField(blank=True, max_length=288, null=True)),
                ('education', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=588, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=588, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=588, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
