# Generated by Django 3.1.1 on 2020-10-15 18:19

from django.db import migrations, models
import userProfile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20201013_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='img',
            field=models.ImageField(blank=True, default='dummy_user.jpeg', null=True, upload_to=userProfile.models.get_file_path_members),
        ),
    ]
