# Generated by Django 3.1.1 on 2020-11-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20201029_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='org/'),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
    ]
