# Generated by Django 3.1.1 on 2020-10-16 14:29

import ckeditor.fields
from django.db import migrations, models
import userProfile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_memberprofile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='education',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='img',
            field=models.ImageField(blank=True, default='uploads/members/default_profile.jpg', null=True, upload_to=userProfile.models.get_file_path_members),
        ),
    ]
