# Generated by Django 3.1.1 on 2020-11-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_auto_20201105_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='address',
            field=models.CharField(blank=True, max_length=288, null=True),
        ),
    ]
