# Generated by Django 3.1.1 on 2020-10-17 15:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_auto_20201016_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='experience',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
