# Generated by Django 3.1.1 on 2020-10-17 15:16

import ckeditor.fields
from django.db import migrations, models
import userProfile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_memberprofile_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='experience',
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='education',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='experience',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='img',
            field=models.ImageField(blank=True, default='uploads/members/default_profile.jpg', null=True, upload_to=userProfile.models.get_file_path_trainers),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='education',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=288, null=True),
        ),
    ]
