# Generated by Django 3.1.1 on 2020-10-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_auto_20201017_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerprofile',
            name='user',
        ),
    ]
