# Generated by Django 3.1.1 on 2020-10-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_remove_trainerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userProfile.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='email',
            field=models.CharField(max_length=288, unique=True),
        ),
    ]
