# Generated by Django 3.1.1 on 2020-11-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='confirm',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
