# Generated by Django 3.1.1 on 2020-09-17 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banner', '0001_initial'),
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.orgprofile'),
        ),
    ]
